### ISSUE TITLE
Doc links are broken

### ISSUE THREAD

**Issue by virtualritz** [ExpHP/slice-of-array#3]
The links in the text to `nest` etc. all lead to nowhere. Both on `docs.rs` as well as when building documentation locally.

Smells like a bug in `cargo-doc` to me as there's no error.

**Comment by ExpHP** [comment]
Interesting.  The link actually has an `href` of `` [`SliceNestExt::nest`] ``, with *literal* square brackets and backticks!  This is because I had (apparently mistakenly) thought that

```
[`name`][`path::to::name`]
```

was a valid way to write one of these links if you wanted to customize the link text.

(I guess I misinterpreted the lack of an error message from `cargo doc` as thinking it was working...!)

---

**Edit:** No wait, I think that syntax does work? (should test this...).  In any case those links at the front of lib.rs are broken because I'm using the footnote syntax:

```
[`name`]: [`path::to::name`]
```

which is normally

```
[`name`]: https://example.com
```

(making the cause for ambiguity fairly obvious)

**Comment by ExpHP** [comment]
[`cargo-deadlinks`](https://github.com/deadlinks/cargo-deadlinks) spots this by the way, so that's a tool I'll be adding to my toolkit.
